### PR TITLE
More helpful error messages.

### PR DESCRIPTION
**Pull request by Cediddi**
This is an example solution to #46 . I also added a test case too.

### CODE REVIEW

**Comment by Cediddi** [comment]
This pr is very small and helpful in exceptional situations. Would you kindly review and merge it, maybe?

**Comment by lisael** [comment]
There's only a flake8 error on a test method redefinition. @Cediddi would you mind renaming `test_optional_methodfield` (or remove the original one if the two tests overlap), so this could be merged ?

**Comment by Cediddi** [comment]
I'll do the changes as soon as possible.

**Comment by Cediddi** [comment]
I'll do the changes as soon as possible.

**Comment by Cediddi** [comment]
I've opened a new PR for #46 and #73 together. Closing this now.

**Pull request closed without merging**
